package com.lixiaoyun.aike.greendaoDB;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lixiaoyun.aike.entity.model.SalesDynamicsModel;

import com.lixiaoyun.aike.greendaoDB.SalesDynamicsModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig salesDynamicsModelDaoConfig;

    private final SalesDynamicsModelDao salesDynamicsModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        salesDynamicsModelDaoConfig = daoConfigMap.get(SalesDynamicsModelDao.class).clone();
        salesDynamicsModelDaoConfig.initIdentityScope(type);

        salesDynamicsModelDao = new SalesDynamicsModelDao(salesDynamicsModelDaoConfig, this);

        registerDao(SalesDynamicsModel.class, salesDynamicsModelDao);
    }
    
    public void clear() {
        salesDynamicsModelDaoConfig.clearIdentityScope();
    }

    public SalesDynamicsModelDao getSalesDynamicsModelDao() {
        return salesDynamicsModelDao;
    }

}
